name: Eleventy Build
on:
  push:
    paths-ignore:
      - README.md
    branches:
      - "master"

jobs:
  build-deploy:
    name: Eleventy Build
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Build
        uses: TartanLlama/actions-eleventy@v1.3
        with:
          args: --output public
          install_dependencies: true

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./public
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
